version: '3'
services:
  
  mysql:
    image: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
